name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: |
          cd frontend
          npm install

      - name: frontend unit test
        run: |
          cd frontend
          npm run test

      - name: Deploy to Render
        if: success()
        run: |
          curl -X POST https://api.render.com/deploy/srv-coqds0sf7o1s73egkb4g?key=boXl2FAjg2U
